### ISSUE TITLE
Core functions don't accept ranges vs. arrays

### ISSUE THREAD

**Issue by pshriwise** [scopatz/pymoab#11]
This code causes failure:

```
    mb = core.Core()
    coord = np.array((1,1,1),dtype='float64')
    vert = mb.create_vertices(coord)
    test_tag = mb.tag_get_handle("Test",1,types.MB_TYPE_INTEGER)
    data = np.array((1,))
    mb.tag_set_data(test_tag,vert,data)
```

```
TypeError: Argument 'entity_handles' has incorrect type (expected numpy.ndarray, got pymoab.range.Range)
```

Unless you convert the range returned from mb.create_vertices to a numpy array of dtype uint64 before trying to set data on it.

**Comment by scopatz** [comment]
The type-checking should probably be done manually in the function body then, rather than in the signature.

**Comment by pshriwise** [comment]
I see. I wasn't aware you could allow type-less arguments in cython function prototypes. This was an easier fix than I thought. See #12.

**Comment by scopatz** [comment]
Yeah, untyped argument, in fact, are just `PyObject *`, ie normal Python objects.
