### ISSUE TITLE
bit tags

### ISSUE THREAD

**Issue by pshriwise** [scopatz/pymoab#7]
MOAB supports tagging of elements with bit data. Currently, I don't see a clear way to make a pure bit array using numpy. 

It seems that the best way would be to convert the bit data to a bool array and then covert it to bits inside the core interface under the hood. This runs a risk of eating up larger amount of memory however and kind of obscures things. Any thoughts?

**Comment by scopatz** [comment]
There is no such thing as a bit array in numpy because there is no such thing as bit data type in C/C++.  Typically this is accomplished by using char as the dtype.  What does MOAB do for bits? I would imagine it also uses char.  Or does it use bool (which still take up a full byte)?  Or does the bit array use std::vector<bool>?  In this case a numpy array of char is the best fit.

**Comment by vijaysm** [comment]
MOAB internally has a specialization for Bit Tags. These are however stored
and returned to the user as char arrays but we do utilize bit shifting to
store them individually. Or at least that is my understanding.

ftp://ftp.mcs.anl.gov/pub/fathom/moab-docs/classmoab_1_1BitPage.html#afca78b3a24c37a959cf7ec9c4e581b71

I think for our purposes, storing a char array in Python should suffice. I
don't see why this could be a problem.

**Comment by scopatz** [comment]
sounds right to me.  There is a python packaged called bitarray that provides a numpy-like interface to bit arrays, if you want to use that instead.

**Comment by pshriwise** [comment]
Hey guys. After reading them and doing a little more research it seems that numpy can do this the same as MOAB. It just goes a bit outside the typical use case. Sorry for the confusion. Probably more of a dev list kind of thing if we had one rather than an issue. This was something I was hung up on today in adding tag_get_data to the interface. Thank you for your replies! Closing...
